// src/pages/Register.tsx

import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { toast } from "sonner";
import { UserType } from "@/types/auth";

const Register = () => {
  const navigate = useNavigate();
  const [userType, setUserType] = useState<UserType>("patient");
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const handleRegister = (e: React.FormEvent) => {
    e.preventDefault();
    if (formData.password !== formData.confirmPassword) {
      toast.error("Passwords do not match");
      return;
    }
    // In a real app, send registration data to backend
    toast.success("Registration successful!");
    navigate("/login");
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prev) => ({
      ...prev,
      [e.target.id]: e.target.value,
    }));
  };

  return (
    <div className="auth-container">
      <div className="absolute top-8 left-1/2 -translate-x-1/2">
        <h1 className="text-4xl font-bold text-primary tracking-tight">
          DocPatient
        </h1>
        <p className="text-muted-foreground text-center mt-1">
          Your Healthcare Connection
        </p>
      </div>
      <Card className="auth-card">
        <CardHeader className="space-y-1">
          <CardTitle className="auth-title">Create your account</CardTitle>
          <CardDescription className="auth-subtitle">
            Join DocPatient as a patient or healthcare provider
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleRegister} className="space-y-6">
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <Button
                  type="button"
                  variant={userType === "patient" ? "default" : "outline"}
                  className="w-full relative overflow-hidden group"
                  onClick={() => setUserType("patient")}
                >
                  <span className="relative z-10">Patient</span>
                  {userType === "patient" && (
                    <div className="absolute inset-0 bg-primary/10 animate-pulse" />
                  )}
                </Button>
                <Button
                  type="button"
                  variant={userType === "doctor" ? "default" : "outline"}
                  className="w-full relative overflow-hidden group"
                  onClick={() => setUserType("doctor")}
                >
                  <span className="relative z-10">Doctor</span>
                  {userType === "doctor" && (
                    <div className="absolute inset-0 bg-primary/10 animate-pulse" />
                  )}
                </Button>
              </div>
              <div className="space-y-2">
                <Label htmlFor="name">Full Name</Label>
                <Input
                  id="name"
                  placeholder="John Doe"
                  value={formData.name}
                  onChange={handleChange}
                  className="transition-all duration-200 focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="name@example.com"
                  value={formData.email}
                  onChange={handleChange}
                  className="transition-all duration-200 focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  value={formData.password}
                  onChange={handleChange}
                  className="transition-all duration-200 focus:ring-2 focus:ring-primary/20"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  className="transition-all duration-200 focus:ring-2 focus:ring-primary/20"
                />
              </div>
            </div>
            <Button 
              type="submit" 
              className="w-full transition-all duration-200 hover:scale-[1.02] active:scale-[0.98]"
            >
              Create account
            </Button>
            <div className="text-center text-sm text-muted-foreground">
              Already have an account?{" "}
              <Link
                to="/login"
                className="text-primary hover:underline font-medium transition-colors"
              >
                Sign in
              </Link>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
};

export default Register;

// src/app/register/register.component.ts

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  registerForm: FormGroup;
  userType: 'patient' | 'doctor' = 'patient';

  constructor(
    private fb: FormBuilder,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required]
    }, {
      validator: this.passwordMatchValidator
    });
  }

  ngOnInit(): void {}

  passwordMatchValidator(g: FormGroup) {
    return g.get('password')?.value === g.get('confirmPassword')?.value
      ? null
      : { mismatch: true };
  }

  setUserType(type: 'patient' | 'doctor'): void {
    this.userType = type;
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      // In a real app, send registration data to backend
      console.log(this.registerForm.value);
      // Show success message using your preferred toast library
      this.router.navigate(['/login']);
    }
  }
}


<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-cyan-100 via-white to-blue-100 relative">
  <div class="absolute top-8 left-1/2 -translate-x-1/2">
    <h1 class="text-4xl font-bold text-cyan-500 tracking-tight">
      DocPatient
    </h1>
    <p class="text-gray-500 text-center mt-1">
      Your Healthcare Connection
    </p>
  </div>

  <div class="w-full max-w-md p-8 bg-white/80 rounded-2xl shadow-lg border border-gray-200 backdrop-blur-sm animate-fadeIn">
    <div class="space-y-1 mb-8">
      <h2 class="text-3xl font-semibold text-center mb-2 bg-gradient-to-r from-cyan-500 to-blue-500 text-transparent bg-clip-text">
        Create your account
      </h2>
      <p class="text-sm text-center text-gray-500">
        Join DocPatient as a patient or healthcare provider
      </p>
    </div>

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-6">
      <div class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <button
            type="button"
            [class]="userType === 'patient' ? 'btn-primary' : 'btn-outline'"
            class="w-full relative overflow-hidden group"
            (click)="setUserType('patient')"
          >
            <span class="relative z-10">Patient</span>
            <div *ngIf="userType === 'patient'" class="absolute inset-0 bg-cyan-500/10 animate-pulse"></div>
          </button>
          <button
            type="button"
            [class]="userType === 'doctor' ? 'btn-primary' : 'btn-outline'"
            class="w-full relative overflow-hidden group"
            (click)="setUserType('doctor')"
          >
            <span class="relative z-10">Doctor</span>
            <div *ngIf="userType === 'doctor'" class="absolute inset-0 bg-cyan-500/10 animate-pulse"></div>
          </button>
        </div>

        <div class="space-y-2">
          <label for="name" class="block text-sm font-medium text-gray-700">Full Name</label>
          <input
            id="name"
            formControlName="name"
            type="text"
            placeholder="John Doe"
            class="input-field"
          />
        </div>

        <div class="space-y-2">
          <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
          <input
            id="email"
            formControlName="email"
            type="email"
            placeholder="name@example.com"
            class="input-field"
          />
        </div>

        <div class="space-y-2">
          <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
          <input
            id="password"
            formControlName="password"
            type="password"
            class="input-field"
          />
        </div>

        <div class="space-y-2">
          <label for="confirmPassword" class="block text-sm font-medium text-gray-700">Confirm Password</label>
          <input
            id="confirmPassword"
            formControlName="confirmPassword"
            type="password"
            class="input-field"
          />
        </div>
      </div>

      <button 
        type="submit"
        [disabled]="!registerForm.valid"
        class="w-full btn-primary transition-all duration-200 hover:scale-[1.02] active:scale-[0.98]"
      >
        Create account
      </button>

      <div class="text-center text-sm text-gray-500">
        Already have an account?
        <a
          routerLink="/login"
          class="text-cyan-500 hover:underline font-medium transition-colors ml-1"
        >
          Sign in
        </a>
      </div>
    </form>
  </div>
</div>
